"""allowing nulls in current elo field

Revision ID: 15bcaca94e94
Revises: 8574e08bdf51
Create Date: 2026-03-10 20:32:54.429080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bcaca94e94'
down_revision: Union[str, None] = '8574e08bdf51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('player', sa.String(length=150), nullable=False),
    sa.Column('atpname', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('hand', sa.String(length=20), nullable=True),
    sa.Column('backhand', sa.String(length=20), nullable=True),
    sa.Column('ioc', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_player'), 'players', ['player'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourney_id', sa.String(length=50), nullable=False),
    sa.Column('tourney_name', sa.String(length=100), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('tourney_level', sa.String(length=10), nullable=False),
    sa.Column('tourney_date', sa.DateTime(), nullable=False),
    sa.Column('match_num', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.String(length=50), nullable=False),
    sa.Column('loser_id', sa.String(length=50), nullable=False),
    sa.Column('winner_name', sa.String(), nullable=True),
    sa.Column('loser_name', sa.String(), nullable=True),
    sa.Column('score', sa.String(length=100), nullable=False),
    sa.Column('best_of', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=10), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('w_ace', sa.Integer(), nullable=True),
    sa.Column('w_df', sa.Integer(), nullable=True),
    sa.Column('w_svpt', sa.Integer(), nullable=True),
    sa.Column('w_1stIn', sa.Integer(), nullable=True),
    sa.Column('w_1stWon', sa.Integer(), nullable=True),
    sa.Column('w_2ndWon', sa.Integer(), nullable=True),
    sa.Column('w_SvGms', sa.Integer(), nullable=True),
    sa.Column('w_bpSaved', sa.Integer(), nullable=True),
    sa.Column('w_bpFaced', sa.Integer(), nullable=True),
    sa.Column('winner_rank', sa.Integer(), nullable=True),
    sa.Column('winner_ranking_points', sa.Integer(), nullable=True),
    sa.Column('l_ace', sa.Integer(), nullable=True),
    sa.Column('l_df', sa.Integer(), nullable=True),
    sa.Column('l_svpt', sa.Integer(), nullable=True),
    sa.Column('l_1stIn', sa.Integer(), nullable=True),
    sa.Column('l_1stWon', sa.Integer(), nullable=True),
    sa.Column('l_2ndWon', sa.Integer(), nullable=True),
    sa.Column('l_SvGms', sa.Integer(), nullable=True),
    sa.Column('l_bpSaved', sa.Integer(), nullable=True),
    sa.Column('l_bpFaced', sa.Integer(), nullable=True),
    sa.Column('loser_rank', sa.Integer(), nullable=True),
    sa.Column('loser_ranking_points', sa.Integer(), nullable=True),
    sa.Column('is_retirement', sa.Boolean(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=True),
    sa.Column('games_diff', sa.Integer(), nullable=True),
    sa.Column('game_win_percentage', sa.Float(), nullable=True),
    sa.Column('tiebreaks_played', sa.Integer(), nullable=True),
    sa.Column('tiebreaks_won', sa.Integer(), nullable=True),
    sa.Column('w_elo_before', sa.Float(), nullable=True),
    sa.Column('l_elo_before', sa.Float(), nullable=True),
    sa.Column('w_surface_elo_before', sa.Float(), nullable=True),
    sa.Column('l_surface_elo_before', sa.Float(), nullable=True),
    sa.Column('w_days_off', sa.Integer(), nullable=True),
    sa.Column('l_days_off', sa.Integer(), nullable=True),
    sa.Column('w_surface_days_off', sa.Integer(), nullable=True),
    sa.Column('l_surface_days_off', sa.Integer(), nullable=True),
    sa.Column('w_rolling_match_win_pct', sa.Float(), nullable=True),
    sa.Column('l_rolling_match_win_pct', sa.Float(), nullable=True),
    sa.Column('w_rolling_game_win_pct', sa.Float(), nullable=True),
    sa.Column('l_rolling_game_win_pct', sa.Float(), nullable=True),
    sa.Column('w_rolling_serve_won_pct', sa.Float(), nullable=True),
    sa.Column('w_rolling_ace_per_game', sa.Float(), nullable=True),
    sa.Column('w_rolling_df_per_pt', sa.Float(), nullable=True),
    sa.Column('w_rolling_bp_save_pct', sa.Float(), nullable=True),
    sa.Column('w_rolling_return_won_pct', sa.Float(), nullable=True),
    sa.Column('l_rolling_serve_won_pct', sa.Float(), nullable=True),
    sa.Column('l_rolling_ace_per_game', sa.Float(), nullable=True),
    sa.Column('l_rolling_df_per_pt', sa.Float(), nullable=True),
    sa.Column('l_rolling_bp_save_pct', sa.Float(), nullable=True),
    sa.Column('l_rolling_return_won_pct', sa.Float(), nullable=True),
    sa.Column('w_tournament_fatigue', sa.Integer(), nullable=True),
    sa.Column('l_tournament_fatigue', sa.Integer(), nullable=True),
    sa.Column('b365_w', sa.Float(), nullable=True),
    sa.Column('b365_l', sa.Float(), nullable=True),
    sa.Column('ps_w', sa.Float(), nullable=True),
    sa.Column('ps_l', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_loser_id'), 'matches', ['loser_id'], unique=False)
    op.create_index(op.f('ix_matches_tourney_id'), 'matches', ['tourney_id'], unique=False)
    op.create_index(op.f('ix_matches_winner_id'), 'matches', ['winner_id'], unique=False)
    op.create_table('player_states',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=False),
    sa.Column('current_elo', sa.Float(), nullable=True),
    sa.Column('current_hard_elo', sa.Float(), nullable=True),
    sa.Column('current_clay_elo', sa.Float(), nullable=True),
    sa.Column('current_grass_elo', sa.Float(), nullable=True),
    sa.Column('last_match_date', sa.Date(), nullable=True),
    sa.Column('last_hard_match_date', sa.Date(), nullable=True),
    sa.Column('last_clay_match_date', sa.Date(), nullable=True),
    sa.Column('last_grass_match_date', sa.Date(), nullable=True),
    sa.Column('rolling_match_win_pct', sa.Float(), nullable=True),
    sa.Column('rolling_game_win_pct', sa.Float(), nullable=True),
    sa.Column('rolling_serve_won_pct', sa.Float(), nullable=True),
    sa.Column('rolling_ace_per_game', sa.Float(), nullable=True),
    sa.Column('rolling_df_per_pt', sa.Float(), nullable=True),
    sa.Column('rolling_bp_save_pct', sa.Float(), nullable=True),
    sa.Column('rolling_return_won_pct', sa.Float(), nullable=True),
    sa.Column('current_tournament_fatigue', sa.Float(), server_default='0.0', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_states_player_name'), 'player_states', ['player_name'], unique=False)
    op.create_table('upcoming_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_id', sa.String(), nullable=False),
    sa.Column('p2_id', sa.String(), nullable=False),
    sa.Column('p1_name', sa.String(), nullable=False),
    sa.Column('p2_name', sa.String(), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tournament', sa.String(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('pin_p1', sa.Float(), nullable=True),
    sa.Column('pin_p2', sa.Float(), nullable=True),
    sa.Column('bf_p1', sa.Float(), nullable=True),
    sa.Column('bf_p2', sa.Float(), nullable=True),
    sa.Column('p1_prob', sa.Float(), nullable=False),
    sa.Column('p2_prob', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['p1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p1_id', 'p2_id', 'commence_time', name='_p1_p2_time_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming_matches')
    op.drop_index(op.f('ix_player_states_player_name'), table_name='player_states')
    op.drop_table('player_states')
    op.drop_index(op.f('ix_matches_winner_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_tourney_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_loser_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_players_player'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
