"""add_score_derived_metrics

Revision ID: 17a2c797b03c
Revises: 8f444d4e7550
Create Date: 2026-03-04 09:59:44.980413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a2c797b03c'
down_revision: Union[str, None] = '8f444d4e7550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_retirement', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('total_games', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('games_diff', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('game_win_percentage', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('tiebreaks_played', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('tiebreaks_won', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'tiebreaks_won')
    op.drop_column('matches', 'tiebreaks_played')
    op.drop_column('matches', 'game_win_percentage')
    op.drop_column('matches', 'games_diff')
    op.drop_column('matches', 'total_games')
    op.drop_column('matches', 'is_retirement')
    # ### end Alembic commands ###
