"""create_player_states

Revision ID: 365019950a3e
Revises: 634da00e0faa
Create Date: 2026-03-06 16:33:27.061695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '365019950a3e'
down_revision: Union[str, None] = '634da00e0faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_states',
    sa.Column('player_id', sa.String(length=50), nullable=False),
    sa.Column('player_name', sa.String(length=150), nullable=False),
    sa.Column('current_elo', sa.Float(), nullable=False),
    sa.Column('current_hard_elo', sa.Float(), nullable=False),
    sa.Column('current_clay_elo', sa.Float(), nullable=False),
    sa.Column('current_grass_elo', sa.Float(), nullable=False),
    sa.Column('last_match_date', sa.Date(), nullable=True),
    sa.Column('last_hard_match_date', sa.Date(), nullable=True),
    sa.Column('last_clay_match_date', sa.Date(), nullable=True),
    sa.Column('last_grass_match_date', sa.Date(), nullable=True),
    sa.Column('rolling_match_win_pct', sa.Float(), nullable=False),
    sa.Column('rolling_game_win_pct', sa.Float(), nullable=False),
    sa.Column('performance_buffer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_player_states_player_name'), 'player_states', ['player_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_states_player_name'), table_name='player_states')
    op.drop_table('player_states')
    # ### end Alembic commands ###
