"""removing unneeded columns

Revision ID: 44dbb1205c46
Revises: e183c55073bf
Create Date: 2026-03-03 20:49:12.197041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dbb1205c46'
down_revision: Union[str, None] = 'e183c55073bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'coaches')
    op.drop_column('players', 'turnedpro')
    op.drop_column('players', 'birthplace')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('birthplace', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('turnedpro', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('coaches', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
