"""add_missing_loser_efficiency_cols

Revision ID: 45dbe765d43e
Revises: caf6fe901865
Create Date: 2026-03-04 16:32:39.314762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45dbe765d43e'
down_revision: Union[str, None] = 'caf6fe901865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('l_rolling_serve_won_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_ace_per_game', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_df_per_pt', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_bp_save_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_return_won_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_rolling_return_won_pct')
    op.drop_column('matches', 'l_rolling_bp_save_pct')
    op.drop_column('matches', 'l_rolling_df_per_pt')
    op.drop_column('matches', 'l_rolling_ace_per_game')
    op.drop_column('matches', 'l_rolling_serve_won_pct')
    # ### end Alembic commands ###
