"""allow_nulls_in_player_states

Revision ID: 5f42bf7edab6
Revises: cc1e06d1007d
Create Date: 2026-03-06 16:58:50.948900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f42bf7edab6'
down_revision: Union[str, None] = 'cc1e06d1007d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_states', sa.Column('current_hard_elo', sa.Float(), nullable=True))
    op.add_column('player_states', sa.Column('current_clay_elo', sa.Float(), nullable=True))
    op.add_column('player_states', sa.Column('current_grass_elo', sa.Float(), nullable=True))
    op.add_column('player_states', sa.Column('last_hard_match_date', sa.Date(), nullable=True))
    op.add_column('player_states', sa.Column('last_clay_match_date', sa.Date(), nullable=True))
    op.add_column('player_states', sa.Column('last_grass_match_date', sa.Date(), nullable=True))
    op.alter_column('player_states', 'rolling_match_win_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_game_win_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_serve_won_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_ace_per_game',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_df_per_pt',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_bp_save_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('player_states', 'rolling_return_won_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('player_states', 'current_surf_elo')
    op.drop_column('player_states', 'last_surf_match_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_states', sa.Column('last_surf_match_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('player_states', sa.Column('current_surf_elo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('player_states', 'rolling_return_won_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_bp_save_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_df_per_pt',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_ace_per_game',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_serve_won_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_game_win_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('player_states', 'rolling_match_win_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('player_states', 'last_grass_match_date')
    op.drop_column('player_states', 'last_clay_match_date')
    op.drop_column('player_states', 'last_hard_match_date')
    op.drop_column('player_states', 'current_grass_elo')
    op.drop_column('player_states', 'current_clay_elo')
    op.drop_column('player_states', 'current_hard_elo')
    # ### end Alembic commands ###
