"""adding matches played column

Revision ID: 64f7ad060030
Revises: 47fa2593bd1a
Create Date: 2026-03-15 11:53:29.103887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f7ad060030'
down_revision: Union[str, None] = '47fa2593bd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('w_matches_played', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('l_matches_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_matches_played')
    op.drop_column('matches', 'w_matches_played')
    # ### end Alembic commands ###
