"""rename_match_date_to_commence_time

Revision ID: 7f870b0b079b
Revises: 8b89290d591f
Create Date: 2026-03-10 11:22:22.734524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f870b0b079b'
down_revision: Union[str, None] = '8b89290d591f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_states', 'current_tournament_fatigue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('upcoming_matches', sa.Column('commence_time', sa.DateTime(), nullable=False))
    op.add_column('upcoming_matches', sa.Column('pin_p1', sa.Float(), nullable=True))
    op.add_column('upcoming_matches', sa.Column('pin_p2', sa.Float(), nullable=True))
    op.add_column('upcoming_matches', sa.Column('bf_p1', sa.Float(), nullable=True))
    op.add_column('upcoming_matches', sa.Column('bf_p2', sa.Float(), nullable=True))
    op.alter_column('upcoming_matches', 'synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('upcoming_matches', 'b365_p1')
    op.drop_column('upcoming_matches', 'ps_p2')
    op.drop_column('upcoming_matches', 'match_date')
    op.drop_column('upcoming_matches', 'b365_p2')
    op.drop_column('upcoming_matches', 'round')
    op.drop_column('upcoming_matches', 'ps_p1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming_matches', sa.Column('ps_p1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('upcoming_matches', sa.Column('round', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('upcoming_matches', sa.Column('b365_p2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('upcoming_matches', sa.Column('match_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('upcoming_matches', sa.Column('ps_p2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('upcoming_matches', sa.Column('b365_p1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('upcoming_matches', 'synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('upcoming_matches', 'bf_p2')
    op.drop_column('upcoming_matches', 'bf_p1')
    op.drop_column('upcoming_matches', 'pin_p2')
    op.drop_column('upcoming_matches', 'pin_p1')
    op.drop_column('upcoming_matches', 'commence_time')
    op.alter_column('player_states', 'current_tournament_fatigue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
