"""renaming prob columns

Revision ID: 8574e08bdf51
Revises: e50ca4fc16c4
Create Date: 2026-03-10 12:20:15.796536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8574e08bdf51'
down_revision: Union[str, None] = 'e50ca4fc16c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming_matches', sa.Column('p1_prob', sa.Float(), nullable=False))
    op.add_column('upcoming_matches', sa.Column('p2_prob', sa.Float(), nullable=False))
    op.create_unique_constraint('_p1_p2_time_uc', 'upcoming_matches', ['p1_id', 'p2_id', 'commence_time'])
    op.drop_column('upcoming_matches', 'predicted_p1_prob')
    op.drop_column('upcoming_matches', 'predicted_p2_prob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming_matches', sa.Column('predicted_p2_prob', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('upcoming_matches', sa.Column('predicted_p1_prob', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('_p1_p2_time_uc', 'upcoming_matches', type_='unique')
    op.drop_column('upcoming_matches', 'p2_prob')
    op.drop_column('upcoming_matches', 'p1_prob')
    # ### end Alembic commands ###
