"""add_player_names_to_matches

Revision ID: 940f7545c541
Revises: d094ac4370c9
Create Date: 2026-03-05 15:49:09.292280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940f7545c541'
down_revision: Union[str, None] = 'd094ac4370c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_name', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('loser_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'loser_name')
    op.drop_column('matches', 'winner_name')
    # ### end Alembic commands ###
