"""add_match_num_and_feature_snapshots

Revision ID: a2b101c11a3d
Revises: e0a8b4ad9735
Create Date: 2026-03-04 10:39:53.340017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b101c11a3d'
down_revision: Union[str, None] = 'e0a8b4ad9735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'match_num')
    # ### end Alembic commands ###
