"""add_rolling_efficiency_columns

Revision ID: caf6fe901865
Revises: a2b101c11a3d
Create Date: 2026-03-04 16:16:32.155192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf6fe901865'
down_revision: Union[str, None] = 'a2b101c11a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('w_rolling_serve_won_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_ace_per_game', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_df_per_pt', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_bp_save_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_return_won_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_tournament_fatigue', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('l_tournament_fatigue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_tournament_fatigue')
    op.drop_column('matches', 'w_tournament_fatigue')
    op.drop_column('matches', 'w_rolling_return_won_pct')
    op.drop_column('matches', 'w_rolling_bp_save_pct')
    op.drop_column('matches', 'w_rolling_df_per_pt')
    op.drop_column('matches', 'w_rolling_ace_per_game')
    op.drop_column('matches', 'w_rolling_serve_won_pct')
    # ### end Alembic commands ###
