"""final_feature_snapshot_table

Revision ID: cc1e06d1007d
Revises: 365019950a3e
Create Date: 2026-03-06 16:49:28.595935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1e06d1007d'
down_revision: Union[str, None] = '365019950a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_states', sa.Column('current_surf_elo', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('last_surf_match_date', sa.Date(), nullable=True))
    op.add_column('player_states', sa.Column('rolling_serve_won_pct', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('rolling_ace_per_game', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('rolling_df_per_pt', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('rolling_bp_save_pct', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('rolling_return_won_pct', sa.Float(), nullable=False))
    op.add_column('player_states', sa.Column('current_tournament_fatigue', sa.Float(), nullable=False))
    op.drop_column('player_states', 'last_hard_match_date')
    op.drop_column('player_states', 'last_grass_match_date')
    op.drop_column('player_states', 'current_grass_elo')
    op.drop_column('player_states', 'performance_buffer')
    op.drop_column('player_states', 'current_clay_elo')
    op.drop_column('player_states', 'last_clay_match_date')
    op.drop_column('player_states', 'current_hard_elo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_states', sa.Column('current_hard_elo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_states', sa.Column('last_clay_match_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('player_states', sa.Column('current_clay_elo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_states', sa.Column('performance_buffer', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('player_states', sa.Column('current_grass_elo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player_states', sa.Column('last_grass_match_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('player_states', sa.Column('last_hard_match_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('player_states', 'current_tournament_fatigue')
    op.drop_column('player_states', 'rolling_return_won_pct')
    op.drop_column('player_states', 'rolling_bp_save_pct')
    op.drop_column('player_states', 'rolling_df_per_pt')
    op.drop_column('player_states', 'rolling_ace_per_game')
    op.drop_column('player_states', 'rolling_serve_won_pct')
    op.drop_column('player_states', 'last_surf_match_date')
    op.drop_column('player_states', 'current_surf_elo')
    # ### end Alembic commands ###
