"""use_jsonb_for_rolling_performance

Revision ID: cfd2a7082bd8
Revises: 17a2c797b03c
Create Date: 2026-03-04 10:21:35.183233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd2a7082bd8'
down_revision: Union[str, None] = '17a2c797b03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
