"""add_surface_days_off_columns

Revision ID: d094ac4370c9
Revises: 3da1b1f2a4da
Create Date: 2026-03-05 11:39:21.984104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd094ac4370c9'
down_revision: Union[str, None] = '3da1b1f2a4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('w_surface_days_off', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('l_surface_days_off', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_surface_days_off')
    op.drop_column('matches', 'w_surface_days_off')
    # ### end Alembic commands ###
