"""add_surface_specific_ml_snapshots

Revision ID: e0a8b4ad9735
Revises: cfd2a7082bd8
Create Date: 2026-03-04 10:25:54.406203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a8b4ad9735'
down_revision: Union[str, None] = 'cfd2a7082bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('w_elo_before', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_elo_before', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_surface_elo_before', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_surface_elo_before', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_days_off', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('l_days_off', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_match_win_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_match_win_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('w_rolling_game_win_pct', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('l_rolling_game_win_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_rolling_game_win_pct')
    op.drop_column('matches', 'w_rolling_game_win_pct')
    op.drop_column('matches', 'l_rolling_match_win_pct')
    op.drop_column('matches', 'w_rolling_match_win_pct')
    op.drop_column('matches', 'l_days_off')
    op.drop_column('matches', 'w_days_off')
    op.drop_column('matches', 'l_surface_elo_before')
    op.drop_column('matches', 'w_surface_elo_before')
    op.drop_column('matches', 'l_elo_before')
    op.drop_column('matches', 'w_elo_before')
    # ### end Alembic commands ###
